#!/usr/bin/env bash
if [ "$#" -ne 1 ]; then
    echo "Usage: ./runexp 1 > run1.log"
    exit 1
fi
query=(1 3 4 6 14 16 17 18 19 22)
for id in ${query[@]}
do
    (cd ../../src/HorseIR/backend && ./run release $1 $id)
done

