SELECT nation      AS nation, 
       o_year      AS o_year, 
       Sum(amount) AS sum_profit 
FROM   (SELECT n_name 
                      AS 
                      nation, 
               Extract(year FROM o_orderdate) 
                      AS o_year, 
               ( ( l_extendedprice * ( 1 - l_discount ) ) - ( 
                 ps_supplycost * l_quantity ) ) AS 
               amount 
        FROM   (SELECT _tmp_a327aebc.s_suppkey       AS s_suppkey, 
                       _tmp_a327aebc.s_name          AS s_name, 
                       _tmp_a327aebc.s_address       AS s_address, 
                       _tmp_a327aebc.s_nationkey     AS s_nationkey, 
                       _tmp_a327aebc.s_phone         AS s_phone, 
                       _tmp_a327aebc.s_acctbal       AS s_acctbal, 
                       _tmp_a327aebc.s_comment       AS s_comment, 
                       _tmp_a327aebc.l_orderkey      AS l_orderkey, 
                       _tmp_a327aebc.l_partkey       AS l_partkey, 
                       _tmp_a327aebc.l_suppkey       AS l_suppkey, 
                       _tmp_a327aebc.l_linenumber    AS l_linenumber, 
                       _tmp_a327aebc.l_quantity      AS l_quantity, 
                       _tmp_a327aebc.l_extendedprice AS l_extendedprice, 
                       _tmp_a327aebc.l_discount      AS l_discount, 
                       _tmp_a327aebc.l_tax           AS l_tax, 
                       _tmp_a327aebc.l_returnflag    AS l_returnflag, 
                       _tmp_a327aebc.l_linestatus    AS l_linestatus, 
                       _tmp_a327aebc.l_shipdate      AS l_shipdate, 
                       _tmp_a327aebc.l_commitdate    AS l_commitdate, 
                       _tmp_a327aebc.l_receiptdate   AS l_receiptdate, 
                       _tmp_a327aebc.l_shipinstruct  AS l_shipinstruct, 
                       _tmp_a327aebc.l_shipmode      AS l_shipmode, 
                       _tmp_a327aebc.l_comment       AS l_comment, 
                       _tmp_a327aebc.ps_partkey      AS ps_partkey, 
                       _tmp_a327aebc.ps_suppkey      AS ps_suppkey, 
                       _tmp_a327aebc.ps_availqty     AS ps_availqty, 
                       _tmp_a327aebc.ps_supplycost   AS ps_supplycost, 
                       _tmp_a327aebc.ps_comment      AS ps_comment, 
                       _tmp_a327aebc.p_partkey       AS p_partkey, 
                       _tmp_a327aebc.p_name          AS p_name, 
                       _tmp_a327aebc.p_mfgr          AS p_mfgr, 
                       _tmp_a327aebc.p_brand         AS p_brand, 
                       _tmp_a327aebc.p_type          AS p_type, 
                       _tmp_a327aebc.p_size          AS p_size, 
                       _tmp_a327aebc.p_container     AS p_container, 
                       _tmp_a327aebc.p_retailprice   AS p_retailprice, 
                       _tmp_a327aebc.p_comment       AS p_comment, 
                       _tmp_a327aebc.o_orderkey      AS o_orderkey, 
                       _tmp_a327aebc.o_custkey       AS o_custkey, 
                       _tmp_a327aebc.o_orderstatus   AS o_orderstatus, 
                       _tmp_a327aebc.o_totalprice    AS o_totalprice, 
                       _tmp_a327aebc.o_orderdate     AS o_orderdate, 
                       _tmp_a327aebc.o_orderpriority AS o_orderpriority, 
                       _tmp_a327aebc.o_clerk         AS o_clerk, 
                       _tmp_a327aebc.o_shippriority  AS o_shippriority, 
                       _tmp_a327aebc.o_comment       AS o_comment, 
                       nation.n_nationkey            AS n_nationkey, 
                       nation.n_name                 AS n_name, 
                       nation.n_regionkey            AS n_regionkey, 
                       nation.n_comment              AS n_comment 
                FROM   (SELECT _tmp_a15caa74.s_suppkey       AS s_suppkey, 
                               _tmp_a15caa74.s_name          AS s_name, 
                               _tmp_a15caa74.s_address       AS s_address, 
                               _tmp_a15caa74.s_nationkey     AS s_nationkey, 
                               _tmp_a15caa74.s_phone         AS s_phone, 
                               _tmp_a15caa74.s_acctbal       AS s_acctbal, 
                               _tmp_a15caa74.s_comment       AS s_comment, 
                               _tmp_a15caa74.l_orderkey      AS l_orderkey, 
                               _tmp_a15caa74.l_partkey       AS l_partkey, 
                               _tmp_a15caa74.l_suppkey       AS l_suppkey, 
                               _tmp_a15caa74.l_linenumber    AS l_linenumber, 
                               _tmp_a15caa74.l_quantity      AS l_quantity, 
                               _tmp_a15caa74.l_extendedprice AS l_extendedprice, 
                               _tmp_a15caa74.l_discount      AS l_discount, 
                               _tmp_a15caa74.l_tax           AS l_tax, 
                               _tmp_a15caa74.l_returnflag    AS l_returnflag, 
                               _tmp_a15caa74.l_linestatus    AS l_linestatus, 
                               _tmp_a15caa74.l_shipdate      AS l_shipdate, 
                               _tmp_a15caa74.l_commitdate    AS l_commitdate, 
                               _tmp_a15caa74.l_receiptdate   AS l_receiptdate, 
                               _tmp_a15caa74.l_shipinstruct  AS l_shipinstruct, 
                               _tmp_a15caa74.l_shipmode      AS l_shipmode, 
                               _tmp_a15caa74.l_comment       AS l_comment, 
                               _tmp_a15caa74.ps_partkey      AS ps_partkey, 
                               _tmp_a15caa74.ps_suppkey      AS ps_suppkey, 
                               _tmp_a15caa74.ps_availqty     AS ps_availqty, 
                               _tmp_a15caa74.ps_supplycost   AS ps_supplycost, 
                               _tmp_a15caa74.ps_comment      AS ps_comment, 
                               _tmp_a15caa74.p_partkey       AS p_partkey, 
                               _tmp_a15caa74.p_name          AS p_name, 
                               _tmp_a15caa74.p_mfgr          AS p_mfgr, 
                               _tmp_a15caa74.p_brand         AS p_brand, 
                               _tmp_a15caa74.p_type          AS p_type, 
                               _tmp_a15caa74.p_size          AS p_size, 
                               _tmp_a15caa74.p_container     AS p_container, 
                               _tmp_a15caa74.p_retailprice   AS p_retailprice, 
                               _tmp_a15caa74.p_comment       AS p_comment, 
                               orders.o_orderkey             AS o_orderkey, 
                               orders.o_custkey              AS o_custkey, 
                               orders.o_orderstatus          AS o_orderstatus, 
                               orders.o_totalprice           AS o_totalprice, 
                               orders.o_orderdate            AS o_orderdate, 
                               orders.o_orderpriority        AS o_orderpriority, 
                               orders.o_clerk                AS o_clerk, 
                               orders.o_shippriority         AS o_shippriority, 
                               orders.o_comment              AS o_comment 
                        FROM   (SELECT _tmp_75af6f9a.s_suppkey       AS 
                                       s_suppkey, 
                                       _tmp_75af6f9a.s_name          AS s_name, 
                                       _tmp_75af6f9a.s_address       AS 
                                       s_address, 
                                       _tmp_75af6f9a.s_nationkey     AS 
                                       s_nationkey, 
                                       _tmp_75af6f9a.s_phone         AS s_phone, 
                                       _tmp_75af6f9a.s_acctbal       AS 
                                       s_acctbal, 
                                       _tmp_75af6f9a.s_comment       AS 
                                       s_comment, 
                                       _tmp_75af6f9a.l_orderkey      AS 
                                       l_orderkey, 
                                       _tmp_75af6f9a.l_partkey       AS 
                                       l_partkey, 
                                       _tmp_75af6f9a.l_suppkey       AS 
                                       l_suppkey, 
                                       _tmp_75af6f9a.l_linenumber    AS 
                                       l_linenumber, 
                                       _tmp_75af6f9a.l_quantity      AS 
                                       l_quantity, 
                                       _tmp_75af6f9a.l_extendedprice AS 
                                       l_extendedprice 
                                       , 
       _tmp_75af6f9a.l_discount      AS l_discount, 
       _tmp_75af6f9a.l_tax           AS l_tax, 
       _tmp_75af6f9a.l_returnflag    AS l_returnflag, 
       _tmp_75af6f9a.l_linestatus    AS l_linestatus, 
       _tmp_75af6f9a.l_shipdate      AS l_shipdate, 
       _tmp_75af6f9a.l_commitdate    AS l_commitdate, 
       _tmp_75af6f9a.l_receiptdate   AS l_receiptdate, 
       _tmp_75af6f9a.l_shipinstruct  AS l_shipinstruct, 
       _tmp_75af6f9a.l_shipmode      AS l_shipmode, 
       _tmp_75af6f9a.l_comment       AS l_comment, 
       _tmp_75af6f9a.ps_partkey      AS ps_partkey, 
       _tmp_75af6f9a.ps_suppkey      AS ps_suppkey, 
       _tmp_75af6f9a.ps_availqty     AS ps_availqty, 
       _tmp_75af6f9a.ps_supplycost   AS ps_supplycost, 
       _tmp_75af6f9a.ps_comment      AS ps_comment, 
       _tmp_8c597a96.p_partkey       AS p_partkey, 
       _tmp_8c597a96.p_name          AS p_name, 
       _tmp_8c597a96.p_mfgr          AS p_mfgr, 
       _tmp_8c597a96.p_brand         AS p_brand, 
       _tmp_8c597a96.p_type          AS p_type, 
       _tmp_8c597a96.p_size          AS p_size, 
       _tmp_8c597a96.p_container     AS p_container, 
       _tmp_8c597a96.p_retailprice   AS p_retailprice, 
       _tmp_8c597a96.p_comment       AS p_comment 
       FROM   (SELECT _tmp_7ab95551.s_suppkey       AS s_suppkey, 
               _tmp_7ab95551.s_name          AS s_name, 
               _tmp_7ab95551.s_address       AS s_address, 
               _tmp_7ab95551.s_nationkey     AS s_nationkey, 
               _tmp_7ab95551.s_phone         AS s_phone, 
               _tmp_7ab95551.s_acctbal       AS s_acctbal, 
               _tmp_7ab95551.s_comment       AS s_comment, 
               _tmp_7ab95551.l_orderkey      AS l_orderkey, 
               _tmp_7ab95551.l_partkey       AS l_partkey, 
               _tmp_7ab95551.l_suppkey       AS l_suppkey, 
               _tmp_7ab95551.l_linenumber    AS l_linenumber, 
               _tmp_7ab95551.l_quantity      AS l_quantity, 
               _tmp_7ab95551.l_extendedprice AS l_extendedprice 
               , 
       _tmp_7ab95551.l_discount      AS l_discount, 
       _tmp_7ab95551.l_tax           AS l_tax, 
       _tmp_7ab95551.l_returnflag    AS l_returnflag, 
       _tmp_7ab95551.l_linestatus    AS l_linestatus, 
       _tmp_7ab95551.l_shipdate      AS l_shipdate, 
       _tmp_7ab95551.l_commitdate    AS l_commitdate, 
       _tmp_7ab95551.l_receiptdate   AS l_receiptdate, 
       _tmp_7ab95551.l_shipinstruct  AS l_shipinstruct, 
       _tmp_7ab95551.l_shipmode      AS l_shipmode, 
       _tmp_7ab95551.l_comment       AS l_comment, 
       partsupp.ps_partkey           AS ps_partkey, 
       partsupp.ps_suppkey           AS ps_suppkey, 
       partsupp.ps_availqty          AS ps_availqty, 
       partsupp.ps_supplycost        AS ps_supplycost, 
       partsupp.ps_comment           AS ps_comment 
       FROM   (SELECT supplier.s_suppkey            AS s_suppkey, 
       supplier.s_name               AS s_name, 
       supplier.s_address            AS s_address, 
       supplier.s_nationkey          AS s_nationkey, 
       supplier.s_phone              AS s_phone, 
       supplier.s_acctbal            AS s_acctbal, 
       supplier.s_comment            AS s_comment, 
       _tmp_7008190b.l_orderkey      AS l_orderkey, 
       _tmp_7008190b.l_partkey       AS l_partkey, 
       _tmp_7008190b.l_suppkey       AS l_suppkey, 
       _tmp_7008190b.l_linenumber    AS l_linenumber, 
       _tmp_7008190b.l_quantity      AS l_quantity, 
       _tmp_7008190b.l_extendedprice AS l_extendedprice 
       , 
       _tmp_7008190b.l_discount      AS l_discount, 
       _tmp_7008190b.l_tax           AS l_tax, 
       _tmp_7008190b.l_returnflag    AS l_returnflag, 
       _tmp_7008190b.l_linestatus    AS l_linestatus, 
       _tmp_7008190b.l_shipdate      AS l_shipdate, 
       _tmp_7008190b.l_commitdate    AS l_commitdate, 
       _tmp_7008190b.l_receiptdate   AS l_receiptdate, 
       _tmp_7008190b.l_shipinstruct  AS l_shipinstruct, 
       _tmp_7008190b.l_shipmode      AS l_shipmode, 
       _tmp_7008190b.l_comment       AS l_comment 
       FROM   (SELECT supplier.s_suppkey, 
       supplier.s_name, 
       supplier.s_address, 
       supplier.s_nationkey, 
       supplier.s_phone, 
       supplier.s_acctbal, 
       supplier.s_comment 
       FROM   supplier) supplier 
       INNER JOIN (SELECT lineitem.l_orderkey, 
       lineitem.l_partkey, 
       lineitem.l_suppkey, 
       lineitem.l_linenumber, 
       lineitem.l_quantity, 
       lineitem.l_extendedprice, 
       lineitem.l_discount, 
       lineitem.l_tax, 
       lineitem.l_returnflag, 
       lineitem.l_linestatus, 
       lineitem.l_shipdate, 
       lineitem.l_commitdate, 
       lineitem.l_receiptdate, 
       lineitem.l_shipinstruct, 
       lineitem.l_shipmode, 
       lineitem.l_comment 
       FROM   lineitem) _tmp_7008190b 
       ON supplier.s_suppkey = _tmp_7008190b.l_suppkey) 
       _tmp_7ab95551 
       INNER JOIN (SELECT partsupp.ps_partkey, 
       partsupp.ps_suppkey, 
       partsupp.ps_availqty, 
       partsupp.ps_supplycost, 
       partsupp.ps_comment 
       FROM   partsupp) partsupp 
       ON _tmp_7ab95551.l_suppkey = partsupp.ps_suppkey 
       AND _tmp_7ab95551.l_partkey = partsupp.ps_partkey) 
       _tmp_75af6f9a 
       INNER JOIN (SELECT p_partkey, 
       p_name, 
       p_mfgr, 
       p_brand, 
       p_type, 
       p_size, 
       p_container, 
       p_retailprice, 
       p_comment 
       FROM   (SELECT part.p_partkey, 
       part.p_name, 
       part.p_mfgr, 
       part.p_brand, 
       part.p_type, 
       part.p_size, 
       part.p_container, 
       part.p_retailprice, 
       part.p_comment 
       FROM   part) part 
       WHERE  ( p_name LIKE '%green%' )) _tmp_8c597a96 
       ON _tmp_75af6f9a.l_partkey = _tmp_8c597a96.p_partkey) 
       _tmp_a15caa74 
       INNER JOIN (SELECT orders.o_orderkey, 
       orders.o_custkey, 
       orders.o_orderstatus, 
       orders.o_totalprice, 
       orders.o_orderdate, 
       orders.o_orderpriority, 
       orders.o_clerk, 
       orders.o_shippriority, 
       orders.o_comment 
       FROM   orders) orders 
       ON _tmp_a15caa74.l_orderkey = orders.o_orderkey) _tmp_a327aebc 
       INNER JOIN (SELECT nation.n_nationkey, 
       nation.n_name, 
       nation.n_regionkey, 
       nation.n_comment 
       FROM   nation) nation 
       ON _tmp_a327aebc.s_nationkey = nation.n_nationkey) _tmp_991807e7) 
       _tmp_716b2a59 
GROUP  BY nation, 
          o_year 
ORDER  BY nation, 
          o_year DESC 
