include(GenerateAntlr4Grammar)
GenerateANTLR4Grammar(horseIR "${CMAKE_CURRENT_SOURCE_DIR}/grammar/HorseIR.g4")
include_directories(${ANTLR4_GEN_DIR})
list(REMOVE_ITEM ANTLR4_horseIR_SOURCE ${ANTLR4_GEN_DIR}/HorseIRListener.cpp)
list(REMOVE_ITEM ANTLR4_horseIR_SOURCE ${ANTLR4_GEN_DIR}/HorseIRVisitor.cpp)
list(REMOVE_ITEM ANTLR4_horseIR_SOURCE ${ANTLR4_GEN_DIR}/HorseIRBaseListener.cpp)
list(REMOVE_ITEM ANTLR4_horseIR_SOURCE ${ANTLR4_GEN_DIR}/HorseIRBaseVisitor.cpp)
foreach(header_file ${ANTLR4_horseIR_HEADER})
  file(COPY ${header_file} DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/include/ast)
endforeach()
