SELECT c_name          AS c_name, 
       c_custkey       AS c_custkey, 
       o_orderkey      AS o_orderkey, 
       o_orderdate     AS o_orderdate, 
       o_totalprice    AS o_totalprice, 
       Sum(l_quantity) AS sum_l_quantity 
FROM   (SELECT c_custkey, 
               c_name, 
               c_address, 
               c_nationkey, 
               c_phone, 
               c_acctbal, 
               c_mktsegment, 
               c_comment, 
               o_orderkey, 
               o_custkey, 
               o_orderstatus, 
               o_totalprice, 
               o_orderdate, 
               o_orderpriority, 
               o_clerk, 
               o_shippriority, 
               o_comment, 
               l_orderkey, 
               l_partkey, 
               l_suppkey, 
               l_linenumber, 
               l_quantity, 
               l_extendedprice, 
               l_discount, 
               l_tax, 
               l_returnflag, 
               l_linestatus, 
               l_shipdate, 
               l_commitdate, 
               l_receiptdate, 
               l_shipinstruct, 
               l_shipmode, 
               l_comment 
        FROM   (SELECT _tmp_28c365a0.c_custkey       AS c_custkey, 
                       _tmp_28c365a0.c_name          AS c_name, 
                       _tmp_28c365a0.c_address       AS c_address, 
                       _tmp_28c365a0.c_nationkey     AS c_nationkey, 
                       _tmp_28c365a0.c_phone         AS c_phone, 
                       _tmp_28c365a0.c_acctbal       AS c_acctbal, 
                       _tmp_28c365a0.c_mktsegment    AS c_mktsegment, 
                       _tmp_28c365a0.c_comment       AS c_comment, 
                       _tmp_28c365a0.o_orderkey      AS o_orderkey, 
                       _tmp_28c365a0.o_custkey       AS o_custkey, 
                       _tmp_28c365a0.o_orderstatus   AS o_orderstatus, 
                       _tmp_28c365a0.o_totalprice    AS o_totalprice, 
                       _tmp_28c365a0.o_orderdate     AS o_orderdate, 
                       _tmp_28c365a0.o_orderpriority AS o_orderpriority, 
                       _tmp_28c365a0.o_clerk         AS o_clerk, 
                       _tmp_28c365a0.o_shippriority  AS o_shippriority, 
                       _tmp_28c365a0.o_comment       AS o_comment, 
                       lineitem.l_orderkey           AS l_orderkey, 
                       lineitem.l_partkey            AS l_partkey, 
                       lineitem.l_suppkey            AS l_suppkey, 
                       lineitem.l_linenumber         AS l_linenumber, 
                       lineitem.l_quantity           AS l_quantity, 
                       lineitem.l_extendedprice      AS l_extendedprice, 
                       lineitem.l_discount           AS l_discount, 
                       lineitem.l_tax                AS l_tax, 
                       lineitem.l_returnflag         AS l_returnflag, 
                       lineitem.l_linestatus         AS l_linestatus, 
                       lineitem.l_shipdate           AS l_shipdate, 
                       lineitem.l_commitdate         AS l_commitdate, 
                       lineitem.l_receiptdate        AS l_receiptdate, 
                       lineitem.l_shipinstruct       AS l_shipinstruct, 
                       lineitem.l_shipmode           AS l_shipmode, 
                       lineitem.l_comment            AS l_comment 
                FROM   (SELECT customer.c_custkey            AS c_custkey, 
                               customer.c_name               AS c_name, 
                               customer.c_address            AS c_address, 
                               customer.c_nationkey          AS c_nationkey, 
                               customer.c_phone              AS c_phone, 
                               customer.c_acctbal            AS c_acctbal, 
                               customer.c_mktsegment         AS c_mktsegment, 
                               customer.c_comment            AS c_comment, 
                               _tmp_9115eacc.o_orderkey      AS o_orderkey, 
                               _tmp_9115eacc.o_custkey       AS o_custkey, 
                               _tmp_9115eacc.o_orderstatus   AS o_orderstatus, 
                               _tmp_9115eacc.o_totalprice    AS o_totalprice, 
                               _tmp_9115eacc.o_orderdate     AS o_orderdate, 
                               _tmp_9115eacc.o_orderpriority AS o_orderpriority, 
                               _tmp_9115eacc.o_clerk         AS o_clerk, 
                               _tmp_9115eacc.o_shippriority  AS o_shippriority, 
                               _tmp_9115eacc.o_comment       AS o_comment 
                        FROM   (SELECT customer.c_custkey, 
                                       customer.c_name, 
                                       customer.c_address, 
                                       customer.c_nationkey, 
                                       customer.c_phone, 
                                       customer.c_acctbal, 
                                       customer.c_mktsegment, 
                                       customer.c_comment 
                                FROM   customer) customer 
                               INNER JOIN (SELECT orders.o_orderkey, 
                                                  orders.o_custkey, 
                                                  orders.o_orderstatus, 
                                                  orders.o_totalprice, 
                                                  orders.o_orderdate, 
                                                  orders.o_orderpriority, 
                                                  orders.o_clerk, 
                                                  orders.o_shippriority, 
                                                  orders.o_comment 
                                           FROM   orders) _tmp_9115eacc 
                                       ON customer.c_custkey = 
                                          _tmp_9115eacc.o_custkey) 
                       _tmp_28c365a0 
                       INNER JOIN (SELECT lineitem.l_orderkey, 
                                          lineitem.l_partkey, 
                                          lineitem.l_suppkey, 
                                          lineitem.l_linenumber, 
                                          lineitem.l_quantity, 
                                          lineitem.l_extendedprice, 
                                          lineitem.l_discount, 
                                          lineitem.l_tax, 
                                          lineitem.l_returnflag, 
                                          lineitem.l_linestatus, 
                                          lineitem.l_shipdate, 
                                          lineitem.l_commitdate, 
                                          lineitem.l_receiptdate, 
                                          lineitem.l_shipinstruct, 
                                          lineitem.l_shipmode, 
                                          lineitem.l_comment 
                                   FROM   lineitem) lineitem 
                               ON _tmp_28c365a0.o_orderkey = 
               lineitem.l_orderkey) 
               _tmp_0946b842 
        WHERE  ( o_orderkey IN (SELECT l_orderkey AS l_orderkey 
                                FROM   (SELECT l_orderkey, 
                                               qty 
                                        FROM   (SELECT l_orderkey      AS 
                                                       l_orderkey, 
                                                       Sum(l_quantity) AS qty 
                                                FROM 
                                       (SELECT lineitem.l_orderkey, 
                                               lineitem.l_partkey, 
                                               lineitem.l_suppkey, 
                                               lineitem.l_linenumber, 
                                               lineitem.l_quantity, 
                                               lineitem.l_extendedprice 
                                               , 
       lineitem.l_discount, 
       lineitem.l_tax, 
       lineitem.l_returnflag, 
       lineitem.l_linestatus, 
       lineitem.l_shipdate, 
       lineitem.l_commitdate, 
       lineitem.l_receiptdate, 
       lineitem.l_shipinstruct, 
       lineitem.l_shipmode, 
       lineitem.l_comment 
       FROM   lineitem) lineitem 
       GROUP  BY l_orderkey) _tmp_b091e71b 
       WHERE  ( qty > 300 )) _tmp_acd6bbc3) )) _tmp_269cdd48 
GROUP  BY c_name, 
          c_custkey, 
          o_orderkey, 
          o_orderdate, 
          o_totalprice 
ORDER  BY o_totalprice DESC, 
          o_orderdate 
LIMIT  100 
