SELECT n_name   AS n_name, 
       Sum(rev) AS revenue 
FROM   (SELECT n_name                                   AS n_name, 
               ( l_extendedprice * ( 1 - l_discount ) ) AS rev 
        FROM   (SELECT _tmp_a994d31b.c_custkey       AS c_custkey, 
                       _tmp_a994d31b.c_name          AS c_name, 
                       _tmp_a994d31b.c_address       AS c_address, 
                       _tmp_a994d31b.c_nationkey     AS c_nationkey, 
                       _tmp_a994d31b.c_phone         AS c_phone, 
                       _tmp_a994d31b.c_acctbal       AS c_acctbal, 
                       _tmp_a994d31b.c_mktsegment    AS c_mktsegment, 
                       _tmp_a994d31b.c_comment       AS c_comment, 
                       _tmp_a994d31b.o_orderkey      AS o_orderkey, 
                       _tmp_a994d31b.o_custkey       AS o_custkey, 
                       _tmp_a994d31b.o_orderstatus   AS o_orderstatus, 
                       _tmp_a994d31b.o_totalprice    AS o_totalprice, 
                       _tmp_a994d31b.o_orderdate     AS o_orderdate, 
                       _tmp_a994d31b.o_orderpriority AS o_orderpriority, 
                       _tmp_a994d31b.o_clerk         AS o_clerk, 
                       _tmp_a994d31b.o_shippriority  AS o_shippriority, 
                       _tmp_a994d31b.o_comment       AS o_comment, 
                       _tmp_a994d31b.l_orderkey      AS l_orderkey, 
                       _tmp_a994d31b.l_partkey       AS l_partkey, 
                       _tmp_a994d31b.l_suppkey       AS l_suppkey, 
                       _tmp_a994d31b.l_linenumber    AS l_linenumber, 
                       _tmp_a994d31b.l_quantity      AS l_quantity, 
                       _tmp_a994d31b.l_extendedprice AS l_extendedprice, 
                       _tmp_a994d31b.l_discount      AS l_discount, 
                       _tmp_a994d31b.l_tax           AS l_tax, 
                       _tmp_a994d31b.l_returnflag    AS l_returnflag, 
                       _tmp_a994d31b.l_linestatus    AS l_linestatus, 
                       _tmp_a994d31b.l_shipdate      AS l_shipdate, 
                       _tmp_a994d31b.l_commitdate    AS l_commitdate, 
                       _tmp_a994d31b.l_receiptdate   AS l_receiptdate, 
                       _tmp_a994d31b.l_shipinstruct  AS l_shipinstruct, 
                       _tmp_a994d31b.l_shipmode      AS l_shipmode, 
                       _tmp_a994d31b.l_comment       AS l_comment, 
                       _tmp_a994d31b.s_suppkey       AS s_suppkey, 
                       _tmp_a994d31b.s_name          AS s_name, 
                       _tmp_a994d31b.s_address       AS s_address, 
                       _tmp_a994d31b.s_nationkey     AS s_nationkey, 
                       _tmp_a994d31b.s_phone         AS s_phone, 
                       _tmp_a994d31b.s_acctbal       AS s_acctbal, 
                       _tmp_a994d31b.s_comment       AS s_comment, 
                       _tmp_a994d31b.n_nationkey     AS n_nationkey, 
                       _tmp_a994d31b.n_name          AS n_name, 
                       _tmp_a994d31b.n_regionkey     AS n_regionkey, 
                       _tmp_a994d31b.n_comment       AS n_comment, 
                       _tmp_bc54632a.r_regionkey     AS r_regionkey, 
                       _tmp_bc54632a.r_name          AS r_name, 
                       _tmp_bc54632a.r_comment       AS r_comment 
                FROM   (SELECT _tmp_65db2362.c_custkey       AS c_custkey, 
                               _tmp_65db2362.c_name          AS c_name, 
                               _tmp_65db2362.c_address       AS c_address, 
                               _tmp_65db2362.c_nationkey     AS c_nationkey, 
                               _tmp_65db2362.c_phone         AS c_phone, 
                               _tmp_65db2362.c_acctbal       AS c_acctbal, 
                               _tmp_65db2362.c_mktsegment    AS c_mktsegment, 
                               _tmp_65db2362.c_comment       AS c_comment, 
                               _tmp_65db2362.o_orderkey      AS o_orderkey, 
                               _tmp_65db2362.o_custkey       AS o_custkey, 
                               _tmp_65db2362.o_orderstatus   AS o_orderstatus, 
                               _tmp_65db2362.o_totalprice    AS o_totalprice, 
                               _tmp_65db2362.o_orderdate     AS o_orderdate, 
                               _tmp_65db2362.o_orderpriority AS o_orderpriority, 
                               _tmp_65db2362.o_clerk         AS o_clerk, 
                               _tmp_65db2362.o_shippriority  AS o_shippriority, 
                               _tmp_65db2362.o_comment       AS o_comment, 
                               _tmp_65db2362.l_orderkey      AS l_orderkey, 
                               _tmp_65db2362.l_partkey       AS l_partkey, 
                               _tmp_65db2362.l_suppkey       AS l_suppkey, 
                               _tmp_65db2362.l_linenumber    AS l_linenumber, 
                               _tmp_65db2362.l_quantity      AS l_quantity, 
                               _tmp_65db2362.l_extendedprice AS l_extendedprice, 
                               _tmp_65db2362.l_discount      AS l_discount, 
                               _tmp_65db2362.l_tax           AS l_tax, 
                               _tmp_65db2362.l_returnflag    AS l_returnflag, 
                               _tmp_65db2362.l_linestatus    AS l_linestatus, 
                               _tmp_65db2362.l_shipdate      AS l_shipdate, 
                               _tmp_65db2362.l_commitdate    AS l_commitdate, 
                               _tmp_65db2362.l_receiptdate   AS l_receiptdate, 
                               _tmp_65db2362.l_shipinstruct  AS l_shipinstruct, 
                               _tmp_65db2362.l_shipmode      AS l_shipmode, 
                               _tmp_65db2362.l_comment       AS l_comment, 
                               _tmp_65db2362.s_suppkey       AS s_suppkey, 
                               _tmp_65db2362.s_name          AS s_name, 
                               _tmp_65db2362.s_address       AS s_address, 
                               _tmp_65db2362.s_nationkey     AS s_nationkey, 
                               _tmp_65db2362.s_phone         AS s_phone, 
                               _tmp_65db2362.s_acctbal       AS s_acctbal, 
                               _tmp_65db2362.s_comment       AS s_comment, 
                               nation.n_nationkey            AS n_nationkey, 
                               nation.n_name                 AS n_name, 
                               nation.n_regionkey            AS n_regionkey, 
                               nation.n_comment              AS n_comment 
                        FROM   (SELECT _tmp_9f4e50fe.c_custkey       AS 
                                       c_custkey, 
                                       _tmp_9f4e50fe.c_name          AS c_name, 
                                       _tmp_9f4e50fe.c_address       AS 
                                       c_address, 
                                       _tmp_9f4e50fe.c_nationkey     AS 
                                       c_nationkey, 
                                       _tmp_9f4e50fe.c_phone         AS c_phone, 
                                       _tmp_9f4e50fe.c_acctbal       AS 
                                       c_acctbal, 
                                       _tmp_9f4e50fe.c_mktsegment    AS 
                                       c_mktsegment, 
                                       _tmp_9f4e50fe.c_comment       AS 
                                       c_comment, 
                                       _tmp_9f4e50fe.o_orderkey      AS 
                                       o_orderkey, 
                                       _tmp_9f4e50fe.o_custkey       AS 
                                       o_custkey, 
                                       _tmp_9f4e50fe.o_orderstatus   AS 
                                       o_orderstatus, 
                                       _tmp_9f4e50fe.o_totalprice    AS 
                                       o_totalprice, 
                                       _tmp_9f4e50fe.o_orderdate     AS 
                                       o_orderdate, 
                                       _tmp_9f4e50fe.o_orderpriority AS 
                                       o_orderpriority 
                                       , 
       _tmp_9f4e50fe.o_clerk         AS o_clerk, 
       _tmp_9f4e50fe.o_shippriority  AS o_shippriority, 
       _tmp_9f4e50fe.o_comment       AS o_comment, 
       _tmp_9f4e50fe.l_orderkey      AS l_orderkey, 
       _tmp_9f4e50fe.l_partkey       AS l_partkey, 
       _tmp_9f4e50fe.l_suppkey       AS l_suppkey, 
       _tmp_9f4e50fe.l_linenumber    AS l_linenumber, 
       _tmp_9f4e50fe.l_quantity      AS l_quantity, 
       _tmp_9f4e50fe.l_extendedprice AS l_extendedprice, 
       _tmp_9f4e50fe.l_discount      AS l_discount, 
       _tmp_9f4e50fe.l_tax           AS l_tax, 
       _tmp_9f4e50fe.l_returnflag    AS l_returnflag, 
       _tmp_9f4e50fe.l_linestatus    AS l_linestatus, 
       _tmp_9f4e50fe.l_shipdate      AS l_shipdate, 
       _tmp_9f4e50fe.l_commitdate    AS l_commitdate, 
       _tmp_9f4e50fe.l_receiptdate   AS l_receiptdate, 
       _tmp_9f4e50fe.l_shipinstruct  AS l_shipinstruct, 
       _tmp_9f4e50fe.l_shipmode      AS l_shipmode, 
       _tmp_9f4e50fe.l_comment       AS l_comment, 
       supplier.s_suppkey            AS s_suppkey, 
       supplier.s_name               AS s_name, 
       supplier.s_address            AS s_address, 
       supplier.s_nationkey          AS s_nationkey, 
       supplier.s_phone              AS s_phone, 
       supplier.s_acctbal            AS s_acctbal, 
       supplier.s_comment            AS s_comment 
       FROM   (SELECT _tmp_c2ddfe06.c_custkey       AS c_custkey, 
               _tmp_c2ddfe06.c_name          AS c_name, 
               _tmp_c2ddfe06.c_address       AS c_address, 
               _tmp_c2ddfe06.c_nationkey     AS c_nationkey, 
               _tmp_c2ddfe06.c_phone         AS c_phone, 
               _tmp_c2ddfe06.c_acctbal       AS c_acctbal, 
               _tmp_c2ddfe06.c_mktsegment    AS c_mktsegment, 
               _tmp_c2ddfe06.c_comment       AS c_comment, 
               _tmp_c2ddfe06.o_orderkey      AS o_orderkey, 
               _tmp_c2ddfe06.o_custkey       AS o_custkey, 
               _tmp_c2ddfe06.o_orderstatus   AS o_orderstatus, 
               _tmp_c2ddfe06.o_totalprice    AS o_totalprice, 
               _tmp_c2ddfe06.o_orderdate     AS o_orderdate, 
               _tmp_c2ddfe06.o_orderpriority AS o_orderpriority 
               , 
       _tmp_c2ddfe06.o_clerk         AS o_clerk, 
       _tmp_c2ddfe06.o_shippriority  AS o_shippriority, 
       _tmp_c2ddfe06.o_comment       AS o_comment, 
       lineitem.l_orderkey           AS l_orderkey, 
       lineitem.l_partkey            AS l_partkey, 
       lineitem.l_suppkey            AS l_suppkey, 
       lineitem.l_linenumber         AS l_linenumber, 
       lineitem.l_quantity           AS l_quantity, 
       lineitem.l_extendedprice      AS l_extendedprice, 
       lineitem.l_discount           AS l_discount, 
       lineitem.l_tax                AS l_tax, 
       lineitem.l_returnflag         AS l_returnflag, 
       lineitem.l_linestatus         AS l_linestatus, 
       lineitem.l_shipdate           AS l_shipdate, 
       lineitem.l_commitdate         AS l_commitdate, 
       lineitem.l_receiptdate        AS l_receiptdate, 
       lineitem.l_shipinstruct       AS l_shipinstruct, 
       lineitem.l_shipmode           AS l_shipmode, 
       lineitem.l_comment            AS l_comment 
       FROM   (SELECT customer.c_custkey            AS c_custkey, 
       customer.c_name               AS c_name, 
       customer.c_address            AS c_address, 
       customer.c_nationkey          AS c_nationkey, 
       customer.c_phone              AS c_phone, 
       customer.c_acctbal            AS c_acctbal, 
       customer.c_mktsegment         AS c_mktsegment, 
       customer.c_comment            AS c_comment, 
       _tmp_d4863fc1.o_orderkey      AS o_orderkey, 
       _tmp_d4863fc1.o_custkey       AS o_custkey, 
       _tmp_d4863fc1.o_orderstatus   AS o_orderstatus, 
       _tmp_d4863fc1.o_totalprice    AS o_totalprice, 
       _tmp_d4863fc1.o_orderdate     AS o_orderdate, 
       _tmp_d4863fc1.o_orderpriority AS o_orderpriority 
       , 
       _tmp_d4863fc1.o_clerk         AS o_clerk, 
       _tmp_d4863fc1.o_shippriority  AS o_shippriority, 
       _tmp_d4863fc1.o_comment       AS o_comment 
       FROM   (SELECT customer.c_custkey, 
       customer.c_name, 
       customer.c_address, 
       customer.c_nationkey, 
       customer.c_phone, 
       customer.c_acctbal, 
       customer.c_mktsegment, 
       customer.c_comment 
       FROM   customer) customer 
       INNER JOIN (SELECT o_orderkey, 
       o_custkey, 
       o_orderstatus, 
       o_totalprice, 
       o_orderdate, 
       o_orderpriority, 
       o_clerk, 
       o_shippriority, 
       o_comment 
       FROM   (SELECT orders.o_orderkey, 
       orders.o_custkey, 
       orders.o_orderstatus, 
       orders.o_totalprice, 
       orders.o_orderdate, 
       orders.o_orderpriority, 
       orders.o_clerk, 
       orders.o_shippriority, 
       orders.o_comment 
       FROM   orders) orders 
       WHERE  ( o_orderdate >= '1994-01-01' ) 
       AND ( o_orderdate < '1995-01-01' )) 
       _tmp_d4863fc1 
       ON customer.c_custkey = _tmp_d4863fc1.o_custkey) 
       _tmp_c2ddfe06 
       INNER JOIN (SELECT lineitem.l_orderkey, 
       lineitem.l_partkey, 
       lineitem.l_suppkey, 
       lineitem.l_linenumber, 
       lineitem.l_quantity, 
       lineitem.l_extendedprice, 
       lineitem.l_discount, 
       lineitem.l_tax, 
       lineitem.l_returnflag, 
       lineitem.l_linestatus, 
       lineitem.l_shipdate, 
       lineitem.l_commitdate, 
       lineitem.l_receiptdate, 
       lineitem.l_shipinstruct, 
       lineitem.l_shipmode, 
       lineitem.l_comment 
       FROM   lineitem) lineitem 
       ON _tmp_c2ddfe06.o_orderkey = lineitem.l_orderkey) 
       _tmp_9f4e50fe 
       INNER JOIN (SELECT supplier.s_suppkey, 
       supplier.s_name, 
       supplier.s_address, 
       supplier.s_nationkey, 
       supplier.s_phone, 
       supplier.s_acctbal, 
       supplier.s_comment 
       FROM   supplier) supplier 
       ON _tmp_9f4e50fe.l_suppkey = supplier.s_suppkey 
       AND _tmp_9f4e50fe.c_nationkey = supplier.s_nationkey) 
       _tmp_65db2362 
       INNER JOIN (SELECT nation.n_nationkey, 
       nation.n_name, 
       nation.n_regionkey, 
       nation.n_comment 
       FROM   nation) nation 
       ON _tmp_65db2362.s_nationkey = nation.n_nationkey) _tmp_a994d31b 
       INNER JOIN (SELECT r_regionkey, 
       r_name, 
       r_comment 
       FROM   (SELECT region.r_regionkey, 
       region.r_name, 
       region.r_comment 
       FROM   region) region 
       WHERE  ( r_name = 'ASIA' )) _tmp_bc54632a 
       ON _tmp_a994d31b.n_regionkey = _tmp_bc54632a.r_regionkey) _tmp_5a36f502) 
       _tmp_819051b6 
GROUP  BY n_name 
ORDER  BY revenue DESC 
