#!/usr/bin/env bash
if [ "$#" -ne 3 ]; then
    echo "Usage: ./runpl [debug|release] [id] [sid]"
    exit 1
fi
echo Starting ...
export OMP_PLACES=cores
export OMP_PROC_BIND=spread
export OMP_NUM_THREADS=4
id=$2
sid=$3
# cmd="./horse -p $id -o -r 10"
cmd="./horse -p $id -u $sid -o"
if [ "debug" == "$1" ]; then
    (cd ../ && make debug   && time $cmd -d ' ')
elif [ "release" == "$1" ]; then
    (cd ../ && make release && time $cmd -d ' ')
else
    (cd ../ && time $cmd -d ' ')
fi
echo Done.
