#!/usr/bin/env bash
if [ "$#" -ne 4 ]; then
    echo "Usage: ./runpl [debug|release] [opt|noopt] [id] [sid]"
    exit 1
fi
echo Starting ...
export OMP_PLACES=cores
export OMP_PROC_BIND=spread
export OMP_NUM_THREADS=4
if [ "$2" = "opt" ]; then
    opt="-o"
fi
id=$3
sid=$4
cmd="./horse -p $id -u $sid $opt"
# cmd="./horse -p $id -u $sid $opt -r 10"
if [ "debug" == "$1" ]; then
    (cd ../ && make debug   && time $cmd -d ' ')
elif [ "release" == "$1" ]; then
    (cd ../ && make TPCH="-DSORT_MERGE" release && time $cmd -d ' ')
else
    (cd ../ && time $cmd -d ' ')
fi
echo Done.
