site_name: HorsePower

theme:
    name: material
    highlihtjs: True
    titles_only: True
    static_templates:
        - 404.html
    palette:
        primary: 'blue grey'
        accent: 'blue grey'
        #primary: 'indigo'
        #accent: 'light blue'

extra:
    font:
        text: 'Helvetica'
        code: 'Roboto Mono'
    author:
        github: 'wukefe'

extra_css: 
    - extra/extra.css
#    - extra/bootstrap.min.css

# mdx_math: https://github.com/mitya57/python-markdown-math
extra_javascript:
    - extra/extra.js
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

# https://squidfunk.github.io/mkdocs-material/extensions/pymdown
# /usr/local/lib/python2.7/site-packages/material
markdown_extensions:
#   - mdx_math
    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.mark
    - admonition
    - toc:
        permalink: True

copyright:
    '&copy; 2017-2019, McGill Sable Research Group <br> Email: <a>hanfeng.chen@mail.mcgill.ca</a> (<a id="chf_page" href="http://www.sable.mcgill.ca/~hanfeng.c/" target="_blank">Hanfeng Chen</a>)'

nav:
- Home    : 'index.md'
- Overview: 'overview.md'
- HorseIR : 
    - Overview     : 'horseir/index.md'
    - Functions    : 'horseir/functions.md'
    - Memory       : 'horseir/memory.md'
    - Database     : 'horseir/database.md'
    - Examples     : 'horseir/examples.md'
- HorseSQL :
    - Overview     : 'sql2ir/index.md'
    - HyPer        : 'sql2ir/hyper.md'
    - MonetDB      : 'sql2ir/monetdb.md'
    - TPC-H        : 'sql2ir/tpch.md'
- HorseSystem : 'system/index.md'
- HorseRuntime: 'runtime/index.md'
- Research:
    - PL           : 'research/pl.md'
    - MMDB         : 'research/mmdb.md'
    - SQL          : 'research/sql.md'
    - Venue        : 'conf/venue.md'
- Summary  : 
    - Lesson       : 'lesson.md'

